### ISSUE TITLE
Help! jquery.js

### ISSUE THREAD

**Issue by alepistola** [aklingspor/supremebot#1]
Hi! I'm trying to understand the using of content scripts by the use of chrome extensions
I have almost understood the "simple" flow of the application but what's the part (the role) of the jquery.js script? I hope you will find free time to answer my dubt . Thank you! @aklingspor

**Comment by aklingspor** [comment]
Hi!

The role of the JQuery.js script is to include the JQuery library into
application, which helps us locate elements to click on and autocomplete
checkout forms.

Let me know if this helps, or if there is anything else I can clarify. Do
you have any suggestions?

This project I still have yet to work on fully, as it is similar to my
yeezybot program.

Anton
